spring:
  application:
    name: InquiryAi
  datasource:
    url: jdbc:mysql://localhost:3306/inquiryai?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: admin